### PR TITLE
module/powerbar: use system-*-symbolic icons for consistency

### PR DESCRIPTION
**Pull request by mochaaP**

### CODE REVIEW

**Comment by jovanlanik** [comment]
I'd have no problem merging this but I worry about `system-suspend-symbolic`. On my system it doesn't exist...

**Comment by jovanlanik** [comment]
What system are you using?

**Comment by mochaaP** [comment]
Seems this is a [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) extension.

Upstream (GNOME) uses `media-playback-pause-symbolic`: <https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/23bcff3348f63c5c10c8d3034665a55b747337c2/js/misc/systemActions.js#L121-128>

**Comment by mochaaP** [comment]
Updated.

**Comment by jovanlanik** [comment]
Great, thank you for the contribution.

**Pull request merged**
